/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.smark.vm.tools.orbd;

import com.sun.tools.visualvm.application.Application;
import javax.swing.InputMap;

/**
 *
 * @author smark
 */
public class ORBDInfoPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrbInfoPanel
     */
    public ORBDInfoPanel() {
        initComponents();
    }
    public ORBDInfoPanel(Application app) {
        initComponents();
        System.out.println("org.smark.vm.tools.orbd.ORBDInfoPanel.<init>():"+app);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        containerPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        namesTree = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        nameInfoPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        nameInfo = new javax.swing.JTextArea();

        setLayout(new java.awt.GridLayout(1, 0));

        containerPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        containerPanel.setLayout(new javax.swing.BoxLayout(containerPanel, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane1.setViewportView(namesTree);
        namesTree.setInputMap(condition, map);

        containerPanel.add(jScrollPane1);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        nameInfoPanel.setLayout(new java.awt.GridLayout(1, 0));

        nameInfo.setColumns(20);
        nameInfo.setRows(5);
        jScrollPane2.setViewportView(nameInfo);

        nameInfoPanel.add(jScrollPane2);

        jPanel2.add(nameInfoPanel);

        containerPanel.add(jPanel2);

        add(containerPanel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel containerPanel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea nameInfo;
    private javax.swing.JPanel nameInfoPanel;
    private javax.swing.JTree namesTree;
    // End of variables declaration//GEN-END:variables
    int condition;
    InputMap  map;
    
}


